[package]
name = "rocket"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
reqwest = "0.11.13"
rocket = { version = "0.5.0-rc.2", features = ["json"] }
serde = "1.0.149"
